### PR TITLE
Add sample Docker Compose environment

### PR DESCRIPTION
**Pull request by shanesveller**
This has already gotten a little scope-creepy so please feel free to keep or
reject as much of the content as you like, and I'm very open to feedback.

### CODE REVIEW

**Comment by shanesveller** [comment]
Current workflow examples that ought to wind up as documentation:
```
docker-compose build ex_venture
docker-compose up
docker-compose run --rm ex_venture migrate
```
Unfortunately this command doesn't currently work in isolation due to the Prometheus Ecto instrumenter and I couldn't readily figure out how to disable it selectively:
```
docker-compose run --rm ex_venture seed
```

File: config/prod.docker.exs [hunk 1]
```diff
@@ -0,0 +1,56 @@
+use Mix.Config
+
+version =
+  case System.cmd("git", ["rev-parse", "HEAD"]) do
+    {version, 0} -> version
+    _ -> System.get_env("APP_VERSION")
+  end
```
Comment (shanesveller) [inline config/prod.docker.exs]: In the current form, the `.git` data is excluded via `.dockerignore` to prevent Docker image caching busts when making new Git commits.

File: config/prod.docker.exs [hunk 2]
```diff
@@ -0,0 +1,56 @@
+use Mix.Config
```
Comment (shanesveller) [inline config/prod.docker.exs]: This net-new file was created to keep the changes in the PR as unintrusive as possible, but may be able to be removed once I get better with Distillery etc.

**Comment by oestrich** [comment]
I can get you the grafana dashboard I have on my main dashboard to include in this later today.

**Comment by shanesveller** [comment]
Once running, the following containers are available:
- Grafana on port `3000` with default credentials `admin`/`admin`
- ExVenture on ports `4000` and `5555`
- Postgres on port `5432`
- Prometheus on port `9090`, scraping ExVenture, Postgres, Grafana and itself

File: Dockerfile [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+RUN npm install
+
+COPY assets /app
+RUN node node_modules/brunch/bin/brunch build --production
+
+FROM builder as releaser
+COPY --from=frontend /priv/static /app/priv/static
+COPY . /app/
+RUN mix phx.digest
+ARG APP_VERSION=0.23.0
```
Comment (shanesveller) [inline Dockerfile]: This can be overridden at build time with:
```
docker-compose build --build-arg APP_VERSION=0.99.0 ex_venture
# or
docker build --build-arg APP_VERSION=0.99.0 -t ex_venture:0.99.0 .
```

File: Dockerfile [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+FROM alpine:3.7
+RUN apk add -U bash libssl1.0
+WORKDIR /app
+COPY --from=releaser /app/_build/prod/rel/ex_venture /app/
+
+ENV MIX_ENV=prod
+
+EXPOSE 4000 5555 5556
+
+VOLUME /var/log/ex_venture/
```
Comment (shanesveller) [inline Dockerfile]: This can probably be omitted from the Logger backend chagnes in `prod.docker.exs`.

File: contrib/grafana/dashboard.yml [hunk 5]
```diff
@@ -0,0 +1,10 @@
+apiVersion: 1
+providers:
+- name: 'default'
+  orgId: 1
+  folder: ''
+  type: file
+  disableDeletion: true
+  updateIntervalSeconds: 3 #how often Grafana will scan for changed dashboards
```
Comment (shanesveller) [inline contrib/grafana/dashboard.yml]: This can be bumped substantially once the dashboard content is nailed down.

**Comment by shanesveller** [comment]
@oestrich I've rebased on `master` and made the additional changes in e638041...c2135a6 but I'm having trouble with the Ranch listener failing when launched in the Docker container with this command sequence:

```shell
docker-compose pull
docker-compose build
docker-compose up -d postgres
docker-compose run --rm ex_venture migrate
docker-compose run --rm ex_venture seed
docker-compose up ex_venture
# observe failure
# destroy environment
docker-compose down -v
```

Errors look like this, but claiming the address/port is in use doesn't make any sense to me at the moment. Might pick this back up in the morning.

```
01:39:25.683 [error] Failed to start Ranch listener #Reference<0.3763471302.2777415682.225172> in :ranch_tcp:listen([port: 5555]) for reason :eaddrinuse (address already in use)
```

**Comment by ringmaster** [comment]
I'm seeing this when I try to start ex_venture after pulling the latest version of this branch:

```
=CRASH REPORT==== 5-Aug-2018::12:51:52 ===
   crasher:
     initial call: Elixir.Game.Features:init/1
     pid: <0.2885.0>
     registered_name: 'Elixir.Game.Features'
     exception error: bad receive timeout value
       in function  gen_server:loop/7 (gen_server.erl, line 389)
     ancestors: ['Elixir.Game.Caches','Elixir.Game.Supervisor',
                   'Elixir.ExVenture.Supervisor',<0.2471.0>]
```

This sort of error seems likely in old versions of Elixir by returning a non-matching value from `init` in a GenServer. Looking at the return value of `Game.Features.init`:

```
{:ok, %{}, {:continue, :load_features}}
```

The third element of the tuple is not a value that my Elixir 1.6 docs say is valid.  This seems to have been added in Elixir 1.7?

I wondered if bumping the image to Elixir 1.7 (and the minimum Elixir version in mix.exs) will correct this issue.  I bumped the Dockerfile to `FROM elixir:1.7-alpine as builder` and attempted a build, but Prometheus failed to compile in this environment (ironically, the same issue when I try to build on local 1.7.1, and the whole reason I was trying this Docker branch in the first place):

```
== Compilation error in file lib/prometheus/erlang.ex ==
** (CompileError) lib/prometheus/erlang.ex:95: __CALLER__ is available only inside defmacro and defmacrop
    lib/prometheus/erlang.ex:95: (module)
could not compile dependency :prometheus_ex, "mix compile" failed. You can recompile this dependency with "mix deps.compile prometheus_ex", update it with "mix deps.update prometheus_ex" or clean it with "mix deps.clean prometheus_ex"
```

The recommendations there solved nothing for me.  I have not delved further into getting Prometheus to build in 1.7.  I assume it's working for someone, though, since this is part of master.  Maybe someone else can point to their obvious (but not to me) solution?

Even if this corrects my build problem, I realize the return value in `init` happens at runtime, so this may not even correct the issue.  I'm having a devil of a time getting this project to simply _turn on_.  😢  But I feel like I'm on the right track here, and hopefully this info is helpful somehow in your next step.

**Comment by shanesveller** [comment]
@ringmaster Anecdotally I've found that the currently-released version of `distillery`, which is used under the hood in the Docker image build, doesn't compile correctly on Elixir 1.7 (even without Docker's involvement). The tip of `master` on Distillery is targeting a 2.0 release with breaking changes so I'm not eager to pull that in just yet.

**Comment by shanesveller** [comment]
My Ranch listener issues wound up being a dumb oversight on my part - forgot to specify that we should run on Elixir 1.6.6 built against Erlang 21. I think, other than documentation, this is finally ready to go from my POV. I'm able to log in from browser and telnet, make myself admin, and otherwise poke around successfully.
