### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by moonsigned** [oestrich/ex_venture#15]
Hi, trying to "mix compile" and getting the following error.

== Compilation error in file lib/game/session/supervisor.ex ==
** (CompileError) lib/game/session/supervisor.ex:6: module DynamicSupervisor is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    lib/game/session/supervisor.ex:6: Game.Session.Supervisor (module)

**Comment by oestrich** [comment]
Are you on elixir 1.6? This project requires it, since dynamic supervisor was introduced it that release.

**Comment by moonsigned** [comment]
Oh, that makes sense. I was following your setup instructions that listed 1.5.2, but I see it’s 1.6 on the main readme. I’ll update it and close this out. Thank you

**Comment by moonsigned** [comment]
Compiled after updating to v1.6.
Thank you

**Comment by oestrich** [comment]
Glad to hear that was it. I updated the setup docs to use 1.6.1 elixir
